os:
- linux
- osx
language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
install: make install
script: make test
notifications:
  slack:
    secure: pStiYmzBbnb0W18r1i1Lz8FIakVHajsv3on1vWy8fNWVuPfaJ85ZqJhnmrr2HKlanZcl6bEMnllDctzt/F+u4HfeXHmhS7a9nZbRDDGyWIxsvJA/UqPt2byLEB1u+KbLb53eDu7MTIe63tzk1zq+4BTupI+btc4igiUuzAhqh4+LP9eZe2L58aC+jOzIn/9Kno7+xawhj2DKs6m3O/hcXFORcOpdtWRFpoDa66dN7xPVbN0hYD80uVApEpghnHToiJN0HhhB92YmZHa1ByWj7u9VN1Eaex1srGQOJQG3FaDBJY1r2e9c7Sj+33gkZb1AqjeOpxhRsxxVUdigDvCoxIrr6ll0/p3n6pUfRGQ7SB1A7NoRBC+g6aTJbOLr5NjQDBmZHaFXx/QFd1h0EUfgBybDI3v4cKOtV8vIFoT1xdkGs/Hjo4v9z4KO6R135uDBwaJAo9cWx360xV1UK1cb4kfzdbJFk4mNmMEbdwJHT27a7e3uWr1lu6CrMUzVk0EXj1BroKC7jcRK7qthr9DcfW2mmGG3JTIKQ6+nYSEF0KC/JjjbIsg/2hKtq7mACzrHrluN6HbqCF6Kd2n2rfItsqIaCo6LEmgZ2fo69R34i96QzyHpplBivWOgC+pwLOe0FiseuleSCZ/kQgJPf62gsqCan6+GkazoEp9Ow+lPMkA=
deploy:
  provider: pypi
  user: pyk
  password:
    secure: gOvN9mx7FnPhepUs6oUAE2dFmV5tZbl9iGjSsBYPl+RNzu5W+UhcJnWvRg2zGs35uF63cs9tjdR7TqYxUk6Jf5SWB7uXrY1I2l2NVFsRGZJkMZ2yxI7zz1SqYzoOh6mn4Zpo/HrLZjAjuo9WQSg07cXIs9iU3n32pfawcMI8ME+zxWnFqvrwsrm+7Q8tPpeavblOVg1D0w4EOpMPmoi8MCzK6syoEQQLfHGG+tdX/gmQ10gsG1cWWeIwTaGFuhv48zFcjjzXAaQ5Ae4DuHyUlHFoPwBjqKS3F6gBumVHltmSyIKRnrKl69K89mui2Yn0oW7sYEOZLLueIEjUsbq5nG/WP0sagq8BWL7c2PpbK4xtKG8DD/bfz9uc/X7aQQAjjZbXiRhJPG3NIJ92Nm22PWr+RezXKP0TSlaIxQfrdyfiz8GtaPe8aVzAqw94EqfxEZCMXRX0ycF4np4o1qNxQKe/V4dybkgaBauBT1cySOk8NjSY8vM2pDTGzfnteIe3/2W7H3tuixhOTDCsHAAhL3il/neKHRAz4yEGSravYID961MnInYU/JgDC1c8lRzem1Jtolp6d94VxyU3i704n4DXn5t44EKJ3gNYFyf8/OSDRs7KJRZoQD0WoWkq2jio+fs6wXjufm7mC3ScUfXNbwcMaC0nihqLTiIiLbgxHgU=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
